package net.sakurain.mc.easytp.rtp.pool;

import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.UUID;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Predicate;

/**
 * Three-tier preload pool for random teleport locations.
 *
 * <ul>
 *   <li>L1 hot pool: validated safe locations whose chunks are currently loaded.</li>
 *   <li>L2 cold pool: validated safe locations whose chunks are not loaded.</li>
 *   <li>L3 candidate queue: coordinates generated by the spiral that still need validation.</li>
 * </ul>
 */
public class RtpPool {

    private volatile int baseSize;
    private volatile double sizeMultiplier;
    private volatile int maxQueuedPlayers;
    private volatile int playerWaitTimeoutMillis;
    private final ConcurrentLinkedQueue<RtpLocation> hotPool = new ConcurrentLinkedQueue<>();
    private final ConcurrentLinkedQueue<RtpLocation> coldPool = new ConcurrentLinkedQueue<>();
    private final ConcurrentLinkedQueue<RtpCandidate> candidateQueue = new ConcurrentLinkedQueue<>();
    private final ConcurrentLinkedQueue<QueuedPlayer> waitingPlayers = new ConcurrentLinkedQueue<>();
    private final AtomicInteger currentCandidateGeneration = new AtomicInteger();

    public RtpPool(int baseSize, double sizeMultiplier, int maxQueuedPlayers, int playerWaitTimeoutSeconds) {
        applyConfig(baseSize, sizeMultiplier, maxQueuedPlayers, playerWaitTimeoutSeconds);
    }

    /**
     * Apply new sizing settings in place, keeping buffered locations and queued players.
     */
    public void applyConfig(int baseSize, double sizeMultiplier, int maxQueuedPlayers, int playerWaitTimeoutSeconds) {
        this.baseSize = Math.max(0, baseSize);
        this.sizeMultiplier = Math.max(0.0, sizeMultiplier);
        this.maxQueuedPlayers = Math.max(1, maxQueuedPlayers);
        this.playerWaitTimeoutMillis = Math.max(5000, playerWaitTimeoutSeconds * 1000);
    }

    /**
     * Count validated locations matching a predicate across the hot and cold pools.
     *
     * <p>Intended for diagnostics only: the queues are traversed without locking and are therefore
     * only weakly consistent during iteration.</p>
     */
    public int countValidated(@NotNull Predicate<RtpLocation> predicate) {
        int count = 0;
        for (RtpLocation location : hotPool) {
            if (predicate.test(location)) {
                count++;
            }
        }
        for (RtpLocation location : coldPool) {
            if (predicate.test(location)) {
                count++;
            }
        }
        return count;
    }

    /**
     * Target number of validated locations the pool should keep ready.
     */
    public int targetSize(int onlinePlayers) {
        return baseSize + (int) Math.round(onlinePlayers * sizeMultiplier);
    }

    /**
     * Total number of validated locations currently buffered.
     */
    public int validatedSize() {
        return hotPool.size() + coldPool.size();
    }

    public int hotSize() {
        return hotPool.size();
    }

    public int coldSize() {
        return coldPool.size();
    }

    public int candidateSize() {
        return candidateQueue.size();
    }

    public int waitingSize() {
        return waitingPlayers.size();
    }

    /**
     * Take a location from the hot pool if one is available.
     */
    @Nullable
    public RtpLocation pollHot() {
        return hotPool.poll();
    }

    /**
     * Take a location from the cold pool if one is available.
     */
    @Nullable
    public RtpLocation pollCold() {
        return coldPool.poll();
    }

    /**
     * Add a validated location to the pool. The location is placed in the hot pool
     * if {@code chunkLoaded} is true, otherwise in the cold pool.
     */
    public void addValidated(@NotNull RtpLocation location, boolean chunkLoaded) {
        if (chunkLoaded) {
            hotPool.offer(location);
        } else {
            coldPool.offer(location);
        }
    }

    /**
     * Offer a new candidate coordinate to the L3 queue.
     */
    public void offerCandidate(@NotNull RtpCandidate candidate) {
        candidateQueue.offer(candidate);
    }

    /**
     * Poll the next candidate coordinate from the L3 queue.
     */
    @Nullable
    public RtpCandidate pollCandidate() {
        return candidateQueue.poll();
    }

    /**
     * Try to add a player to the waiting queue. Returns false if the queue is full.
     */
    public boolean queuePlayer(@NotNull Player player, int generation) {
        if (waitingPlayers.size() >= maxQueuedPlayers) {
            return false;
        }
        waitingPlayers.offer(new QueuedPlayer(player.getUniqueId(), System.currentTimeMillis(), generation));
        return true;
    }

    /**
     * Remove a specific player from the waiting queue.
     */
    public void removePlayer(@NotNull UUID playerId) {
        waitingPlayers.removeIf(q -> q.playerId().equals(playerId));
    }

    /**
     * Put a player back at the end of the waiting queue.
     */
    public void requeuePlayer(@NotNull QueuedPlayer queued) {
        waitingPlayers.offer(queued);
    }

    /**
     * Poll the next waiting player whose request has not timed out.
     * Timed-out entries are silently removed.
     */
    @Nullable
    public QueuedPlayer pollWaitingPlayer() {
        long now = System.currentTimeMillis();
        QueuedPlayer queued;
        while ((queued = waitingPlayers.poll()) != null) {
            if (now - queued.enqueueTime() <= playerWaitTimeoutMillis) {
                return queued;
            }
        }
        return null;
    }

    /**
     * Remove any waiting players whose generation marker is older than the given generation.
     * This is used after a global pool reset to expire stale waiters.
     */
    public void expireStaleWaiters(int currentGeneration) {
        waitingPlayers.removeIf(q -> q.generation() < currentGeneration);
    }

    /**
     * Increment and return the current candidate generation marker.
     */
    public int nextGeneration() {
        return currentCandidateGeneration.incrementAndGet();
    }

    public int currentGeneration() {
        return currentCandidateGeneration.get();
    }

    /**
     * Trim validated pools down to the target size, preferring to keep hot entries.
     */
    public void trimToTarget(int onlinePlayers) {
        int target = targetSize(onlinePlayers);
        int over = validatedSize() - target;
        while (over-- > 0) {
            RtpLocation dropped = coldPool.poll();
            if (dropped == null) {
                dropped = hotPool.poll();
            }
            if (dropped == null) {
                break;
            }
        }
    }

    /**
     * A player waiting for the pool to produce a safe location.
     */
    public record QueuedPlayer(@NotNull UUID playerId, long enqueueTime, int generation) {
    }
}
